### ISSUE TITLE
ONS cannot be parsed: missing import

### ISSUE THREAD

**Issue by matentzn** [enpadasi/Ontology-for-Nutritional-Studies#8]
When trying to load with ROBOT:

```
Could not load imported ontology: <https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/imports/ontofox.owl> Cause: https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/imports/ontofox.owl
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/imports/ontofox.owl> Cause: https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/imports/ontofox.owl
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1870)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TPImportsHandler.handleTriple(TripleHandlers.java:1537)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.handleStreaming(TripleHandlers.java:194)
```

**Comment by FrancescoVit** [comment]
Should be fixed now, wrong URL for imported ontology

**Comment by cmungall** [comment]
Still fails:

```
2021-05-12 18:15:28,430 ERROR (CommandRunner:4815) could not parse:http://purl.obolibrary.org/obo/ons.owl
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/imports/ontodog/obi_in_ons.owl> Cause: https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/imports/ontodog/obi_in_ons.owl
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1870)

```

Consider using PURLs in imports rather than raw github URLs

**Comment by matentzn** [comment]
I would recommend you to merge imports, or at least restrict yourself to using PURLs. Currently, ONS has been failing for the dashboard as well:

http://dashboard.obofoundry.org/dashboard/index.html
